version: '3'
services:
    prometheus:
        image:  prom/prometheus
        ports:
          - "9090:9090"
        volumes:
          - "./prometheus.yml:/etc/prometheus/prometheus.yml"
        networks:
          - bridge

    grafana:
        image:  grafana/grafana
        ports:
          - "3000:3000"
        environment:
          - GF_SECURITY_ADMIN_PASSWORD=p4_int
        networks:
          - bridge

    graphite:
        image:  graphiteapp/graphite-statsd
        ports:
          - "80:80"
          - "2003-2004:2003-2004"
          - "2023-2024:2023-2024"
          - "8125:8125/udp"
          - "8126:8126"
        networks:
          - bridge
networks:
    bridge:
